spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: 'lb://user-service'
          predicates:
            - Path=/users/**
        - id: order-service
          uri: 'lb://order-service'
          predicates:
            - Path=/orders/**
  datasource:
    url: 'jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1'
    driver-class-name: org.h2.Driver
    username: h2
    password: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: h2
eureka:
  client:
    service-url:
      defaultZone: 'http://eurekauser:eurekapass@localhost:8761/eureka/'
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: 'health,info'
